package pages.components.filter;

import java.util.List;

public class BrandsFilterComponent {
    public static final List<String> ALL = List.of(
            "2000 Archives",
            "ASICS",
            "Acne Studios",
            "Adidas",
            "Adidas x Fear of God",
            "Alexander McQueen",
            "Ami",
            "Ami Paris",
            "Amiri",
            "Arc'teryx",
            "Asics",
            "Asics x C.P.Company",
            "BAPE",
            "BPM",
            "Balenciaga",
            "Balenciaga x Adidas",
            "Bape",
            "Bape x Inter",
            "Bape x Comme des Garcons",
            "Bape x Sorayama",
            "Ben Davis",
            "Big Boy",
            "Bigboy",
            "Brockblick",
            "Broken Planet",
            "Burberry",
            "C.P. Company",
            "CK",
            "Calvin Klein",
            "Canada Goose",
            "Carhartt",
            "Cav Empt",
            "Celine",
            "Chao",
            "Chrome Hearts",
            "Coach",
            "Columbia",
            "Comme des Garcons Play",
            "Converse",
            "Corteiz",
            "Crocs",
            "DC Shoes",
            "DGK",
            "Deesmance",
            "Denim",
            "Denim Tears",
            "Dickies",
            "Diesel",
            "Dime",
            "Dr. Martens",
            "EFORTH",
            "ERD",
            "Eastpak",
            "Ellesse",
            "Essentials",
            "Everlane",
            "Evisu",
            "FC Barcelona x Travis Scott",
            "Fade to black",
            "Fcniubi",
            "Fear Of God",
            "Fila",
            "Fred Perry",
            "GAP",
            "Gallery Dept",
            "Gant",
            "Golden Goose",
            "Goyard",
            "Gramicci",
            "Gucci",
            "Haunted Mound",
            "Hellstar",
            "Helly Hansen",
            "Hermes",
            "Hoka",
            "Hugo Boss",
            "Jordan",
            "KEEN Jasper",
            "Kangol",
            "Kanken",
            "Kith",
            "LEGAN",
            "Lacoste",
            "Levi's",
            "Levis",
            "Loro Piana",
            "Lyle Scott",
            "MA.Strum",
            "MLB",
            "Maison Margiela",
            "Maison Margiela x Solomon",
            "Martine Rose",
            "Mastermind Japan x Bape",
            "Mizuno",
            "Moncler",
            "Mont-bell",
            "NBA",
            "NY",
            "New Balance",
            "New Era",
            "New York",
            "Nike Nocta",
            "Nike x Fear Of God",
            "Nobis",
            "North Face x Kaws",
            "Oakley",
            "Ocai",
            "Off White",
            "Off-Whit",
            "Off-White Be Right Back",
            "Old Order",
            "On Cloud",
            "Onitsuka",
            "Optimistic",
            "Orange Dragon FC",
            "Osiris",
            "Palace",
            "Palm Angels",
            "Patagonia",
            "Paul Shark",
            "Play",
            "Polo",
            "Premiata",
            "Project GR Survivor",
            "Puma",
            "Purple Brand",
            "REVENGE",
            "RIPNDIP",
            "Ralph",
            "Ralph Lauren",
            "Reebok",
            "Represent",
            "Rhude",
            "Rick Owens",
            "RipnDip",
            "SUPER SOCKS",
            "Salomon",
            "Saucony",
            "Sea Air",
            "Socool",
            "Sp5der",
            "Spider",
            "Stone Island",
            "Stussy",
            "Stussy x Patta",
            "Supreme",
            "Syna World",
            "The New Line",
            "The North Face",
            "Thrasher",
            "Thug Club",
            "Thug Club x MCM",
            "Timberland",
            "Tommy",
            "Tommy Hilfiger",
            "Trapstar",
            "True Religion",
            "UGG",
            "US Army",
            "Umbro",
            "Undefeated",
            "Under Armour",
            "Vans",
            "Versace",
            "Vetements",
            "Yayihan",
            "Yeezy",
            "Yeezy Gosha",
            "Zara",
            "Zippo",
            "Без бренда"
    );
}
